### ISSUE TITLE
FileNotFoundError in project setup

### ISSUE THREAD

**Issue by ksidht** [RicardoGEsteves/Django-React-Sqlite-SmartDelivery-app#66]
In project setup, i got following error

FileNotFoundError: [Errno 2] No such file or directory: '/backend/env.txt
cmd: python3 src/manage.py makemigrations

**Comment by RicardoGEsteves** [comment]
This project is outdated and not maintained anymore. the logic and structure is still there but you have to implement your own twist.
Update stack and dependencies, and create your own environment variables.
